// Generated by scripts/generate-attributions.mjs — do not edit manually.
// Run: pnpm docs:sync-attributions

export type AttributionPackage = {
  name: string
  version: string
  license: string
  homepage: string
  description: string
  role: string
  category: string
  kind: "runtime" | "development"
}

export type AttributionGroup = {
  title: string
  packages: AttributionPackage[]
}

export type Acknowledgement = {
  name: string
  license: string
  homepage: string
  description: string
}

export const attributionGeneratedAt = "2026-06-11"

export const runtimeAttributionGroups: AttributionGroup[] = [
  {
    "title": "UI primitives & accessibility",
    "packages": [
      {
        "name": "@base-ui/react",
        "version": "1.5.0",
        "license": "MIT",
        "homepage": "https://base-ui.com",
        "description": "Base UI is a library of headless ('unstyled') React components and low-level hooks. You gain complete control over your app's CSS and accessibility features.",
        "role": "Headless React components",
        "category": "UI primitives & accessibility",
        "kind": "runtime"
      },
      {
        "name": "@radix-ui/react-slot",
        "version": "1.2.3",
        "license": "MIT",
        "homepage": "https://radix-ui.com/primitives",
        "description": "",
        "role": "Polymorphic asChild composition",
        "category": "UI primitives & accessibility",
        "kind": "runtime"
      },
      {
        "name": "@radix-ui/react-toast",
        "version": "1.2.14",
        "license": "MIT",
        "homepage": "https://radix-ui.com/primitives",
        "description": "",
        "role": "Toast primitive",
        "category": "UI primitives & accessibility",
        "kind": "runtime"
      },
      {
        "name": "radix-ui",
        "version": "1.5.0",
        "license": "MIT",
        "homepage": "https://radix-ui.com/primitives",
        "description": "",
        "role": "Accessible unstyled primitives (dialogs, menus, etc.)",
        "category": "UI primitives & accessibility",
        "kind": "runtime"
      },
      {
        "name": "vaul",
        "version": "1.1.2",
        "license": "MIT",
        "homepage": "https://vaul.emilkowal.ski/",
        "description": "Drawer component for React.",
        "role": "Drawer component",
        "category": "UI primitives & accessibility",
        "kind": "runtime"
      }
    ]
  },
  {
    "title": "Forms & validation",
    "packages": [
      {
        "name": "@hookform/resolvers",
        "version": "5.4.0",
        "license": "MIT",
        "homepage": "https://react-hook-form.com",
        "description": "React Hook Form validation resolvers: Yup, Joi, Superstruct, Zod, Vest, Class Validator, io-ts, Nope, computed-types, TypeBox, arktype, Typanion, Effect-TS and VineJS",
        "role": "Schema validation adapters",
        "category": "Forms & validation",
        "kind": "runtime"
      },
      {
        "name": "react-hook-form",
        "version": "7.78.0",
        "license": "MIT",
        "homepage": "https://react-hook-form.com",
        "description": "Performant, flexible and extensible forms library for React Hooks",
        "role": "Form state management",
        "category": "Forms & validation",
        "kind": "runtime"
      },
      {
        "name": "zod",
        "version": "3.25.76",
        "license": "MIT",
        "homepage": "https://zod.dev",
        "description": "TypeScript-first schema declaration and validation library with static type inference",
        "role": "Schema validation",
        "category": "Forms & validation",
        "kind": "runtime"
      }
    ]
  },
  {
    "title": "Data tables & charts",
    "packages": [
      {
        "name": "@tanstack/react-table",
        "version": "8.21.3",
        "license": "MIT",
        "homepage": "https://tanstack.com/table",
        "description": "Headless UI for building powerful tables & datagrids for React.",
        "role": "Headless data table engine",
        "category": "Data tables & charts",
        "kind": "runtime"
      },
      {
        "name": "@tanstack/react-virtual",
        "version": "3.14.2",
        "license": "MIT",
        "homepage": "https://tanstack.com/virtual",
        "description": "Headless UI for virtualizing scrollable elements in React",
        "role": "Virtual scrolling for large lists",
        "category": "Data tables & charts",
        "kind": "runtime"
      },
      {
        "name": "recharts",
        "version": "3.8.0",
        "license": "MIT",
        "homepage": "https://github.com/recharts/recharts",
        "description": "React charts",
        "role": "Chart components",
        "category": "Data tables & charts",
        "kind": "runtime"
      }
    ]
  },
  {
    "title": "Date & time",
    "packages": [
      {
        "name": "chrono-node",
        "version": "2.9.1",
        "license": "MIT",
        "homepage": "http://github.com/wanasit/chrono",
        "description": "A natural language date parser in Javascript",
        "role": "Natural language date parsing",
        "category": "Date & time",
        "kind": "runtime"
      },
      {
        "name": "date-fns",
        "version": "4.4.0",
        "license": "MIT",
        "homepage": "https://github.com/date-fns/date-fns",
        "description": "Modern JavaScript date utility library",
        "role": "Date formatting and manipulation",
        "category": "Date & time",
        "kind": "runtime"
      },
      {
        "name": "little-date",
        "version": "1.2.1",
        "license": "MIT",
        "homepage": "https://github.com/vercel/little-date",
        "description": "Small & sweet date-range formatting library",
        "role": "Relative date range formatting",
        "category": "Date & time",
        "kind": "runtime"
      },
      {
        "name": "react-day-picker",
        "version": "10.0.1",
        "license": "MIT",
        "homepage": "https://daypicker.dev",
        "description": "Customizable Date Picker for React",
        "role": "Calendar date picker",
        "category": "Date & time",
        "kind": "runtime"
      }
    ]
  },
  {
    "title": "Styling & class utilities",
    "packages": [
      {
        "name": "class-variance-authority",
        "version": "0.7.1",
        "license": "Apache-2.0",
        "homepage": "https://github.com/joe-bell/cva",
        "description": "Class Variance Authority 🧬",
        "role": "Variant-based component styling",
        "category": "Styling & class utilities",
        "kind": "runtime"
      },
      {
        "name": "clsx",
        "version": "2.1.1",
        "license": "MIT",
        "homepage": "https://github.com/lukeed/clsx",
        "description": "A tiny (239B) utility for constructing className strings conditionally.",
        "role": "Conditional className helper",
        "category": "Styling & class utilities",
        "kind": "runtime"
      },
      {
        "name": "next-themes",
        "version": "0.4.6",
        "license": "MIT",
        "homepage": "https://github.com/pacocoursey/next-themes",
        "description": "",
        "role": "Light/dark theme switching",
        "category": "Styling & class utilities",
        "kind": "runtime"
      },
      {
        "name": "tailwind-merge",
        "version": "3.3.1",
        "license": "MIT",
        "homepage": "https://github.com/dcastil/tailwind-merge",
        "description": "Merge Tailwind CSS classes without style conflicts",
        "role": "Tailwind class conflict resolution",
        "category": "Styling & class utilities",
        "kind": "runtime"
      },
      {
        "name": "tw-animate-css",
        "version": "1.3.6",
        "license": "MIT",
        "homepage": "https://github.com/Wombosvideo/tw-animate-css",
        "description": "TailwindCSS v4.0 compatible replacement for `tailwindcss-animate`.",
        "role": "Tailwind v4 animation utilities",
        "category": "Styling & class utilities",
        "kind": "runtime"
      }
    ]
  },
  {
    "title": "Interaction & components",
    "packages": [
      {
        "name": "cmdk",
        "version": "1.1.1",
        "license": "MIT",
        "homepage": "https://github.com/pacocoursey/cmdk",
        "description": "",
        "role": "Command palette / combobox",
        "category": "Interaction & components",
        "kind": "runtime"
      },
      {
        "name": "embla-carousel-autoplay",
        "version": "8.6.0",
        "license": "MIT",
        "homepage": "https://www.embla-carousel.com",
        "description": "An autoplay plugin for Embla Carousel",
        "role": "Carousel autoplay plugin",
        "category": "Interaction & components",
        "kind": "runtime"
      },
      {
        "name": "embla-carousel-react",
        "version": "8.6.0",
        "license": "MIT",
        "homepage": "https://www.embla-carousel.com",
        "description": "A lightweight carousel library with fluid motion and great swipe precision",
        "role": "Carousel component",
        "category": "Interaction & components",
        "kind": "runtime"
      },
      {
        "name": "input-otp",
        "version": "1.4.2",
        "license": "MIT",
        "homepage": "https://input-otp.rodz.dev/",
        "description": "One-time password input component for React.",
        "role": "One-time password input",
        "category": "Interaction & components",
        "kind": "runtime"
      },
      {
        "name": "react-resizable-panels",
        "version": "4.11.2",
        "license": "MIT",
        "homepage": "https://react-resizable-panels.vercel.app/",
        "description": "",
        "role": "Resizable panel layouts",
        "category": "Interaction & components",
        "kind": "runtime"
      },
      {
        "name": "sonner",
        "version": "2.0.7",
        "license": "MIT",
        "homepage": "https://sonner.emilkowal.ski/",
        "description": "An opinionated toast component for React.",
        "role": "Toast notifications",
        "category": "Interaction & components",
        "kind": "runtime"
      }
    ]
  },
  {
    "title": "Icons",
    "packages": [
      {
        "name": "lucide-react",
        "version": "0.487.0",
        "license": "ISC",
        "homepage": "https://lucide.dev",
        "description": "A Lucide icon library package for React applications",
        "role": "Icon set",
        "category": "Icons",
        "kind": "runtime"
      }
    ]
  },
  {
    "title": "Core framework",
    "packages": [
      {
        "name": "next",
        "version": "15.5.9",
        "license": "MIT",
        "homepage": "https://nextjs.org",
        "description": "The React Framework",
        "role": "App framework for this registry site",
        "category": "Core framework",
        "kind": "runtime"
      },
      {
        "name": "react",
        "version": "19.1.0",
        "license": "MIT",
        "homepage": "https://react.dev/",
        "description": "React is a JavaScript library for building user interfaces.",
        "role": "UI runtime",
        "category": "Core framework",
        "kind": "runtime"
      },
      {
        "name": "react-dom",
        "version": "19.1.0",
        "license": "MIT",
        "homepage": "https://react.dev/",
        "description": "React package for working with the DOM.",
        "role": "DOM rendering",
        "category": "Core framework",
        "kind": "runtime"
      }
    ]
  },
  {
    "title": "Registry & distribution",
    "packages": [
      {
        "name": "shadcn",
        "version": "3.0.0",
        "license": "MIT",
        "homepage": "https://github.com/shadcn/ui",
        "description": "Add components to your apps.",
        "role": "Registry CLI and component distribution",
        "category": "Registry & distribution",
        "kind": "runtime"
      }
    ]
  }
]

export const developmentAttributionGroups: AttributionGroup[] = [
  {
    "title": "Development & tooling",
    "packages": [
      {
        "name": "@eslint/eslintrc",
        "version": "3.3.1",
        "license": "MIT",
        "homepage": "https://github.com/eslint/eslintrc",
        "description": "The legacy ESLintRC config file format for ESLint",
        "role": "Legacy ESLint config support",
        "category": "Development & tooling",
        "kind": "development"
      },
      {
        "name": "@tailwindcss/postcss",
        "version": "4.1.11",
        "license": "MIT",
        "homepage": "https://tailwindcss.com",
        "description": "PostCSS plugin for Tailwind CSS, a utility-first CSS framework for rapidly building custom user interfaces",
        "role": "Tailwind PostCSS integration",
        "category": "Development & tooling",
        "kind": "development"
      },
      {
        "name": "@types/node",
        "version": "20.19.9",
        "license": "MIT",
        "homepage": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node",
        "description": "TypeScript definitions for node",
        "role": "Node.js type definitions",
        "category": "Development & tooling",
        "kind": "development"
      },
      {
        "name": "@types/react",
        "version": "19.1.2",
        "license": "MIT",
        "homepage": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react",
        "description": "TypeScript definitions for react",
        "role": "React type definitions",
        "category": "Development & tooling",
        "kind": "development"
      },
      {
        "name": "@types/react-dom",
        "version": "19.1.2",
        "license": "MIT",
        "homepage": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom",
        "description": "TypeScript definitions for react-dom",
        "role": "React DOM type definitions",
        "category": "Development & tooling",
        "kind": "development"
      },
      {
        "name": "eslint",
        "version": "9.32.0",
        "license": "MIT",
        "homepage": "https://eslint.org",
        "description": "An AST-based pattern checker for JavaScript.",
        "role": "Linting",
        "category": "Development & tooling",
        "kind": "development"
      },
      {
        "name": "eslint-config-next",
        "version": "15.3.1",
        "license": "MIT",
        "homepage": "https://nextjs.org/docs/app/api-reference/config/eslint",
        "description": "ESLint configuration used by Next.js.",
        "role": "Next.js ESLint rules",
        "category": "Development & tooling",
        "kind": "development"
      },
      {
        "name": "tailwindcss",
        "version": "4.1.11",
        "license": "MIT",
        "homepage": "https://tailwindcss.com",
        "description": "A utility-first CSS framework for rapidly building custom user interfaces.",
        "role": "Utility-first CSS framework",
        "category": "Development & tooling",
        "kind": "development"
      },
      {
        "name": "typescript",
        "version": "5.9.2",
        "license": "Apache-2.0",
        "homepage": "https://www.typescriptlang.org/",
        "description": "TypeScript is a language for application scale JavaScript development",
        "role": "Type checking",
        "category": "Development & tooling",
        "kind": "development"
      }
    ]
  }
]

export const acknowledgements: Acknowledgement[] = [
  {
    "name": "shadcn/ui",
    "license": "MIT",
    "homepage": "https://ui.shadcn.com",
    "description": "Component patterns, registry architecture, and CLI that ModernUI extends and distributes."
  },
  {
    "name": "Radix UI",
    "license": "MIT",
    "homepage": "https://radix-ui.com",
    "description": "Accessible, unstyled primitives used across dialogs, menus, popovers, and form controls."
  },
  {
    "name": "TanStack",
    "license": "MIT",
    "homepage": "https://tanstack.com",
    "description": "Headless Table and Virtual libraries for data grids and performant scrolling."
  },
  {
    "name": "Tailwind CSS",
    "license": "MIT",
    "homepage": "https://tailwindcss.com",
    "description": "Utility-first CSS framework and design-token foundation for ModernUI styling."
  },
  {
    "name": "Lucide",
    "license": "ISC",
    "homepage": "https://lucide.dev",
    "description": "Open-source icon set used throughout component examples and docs."
  }
]

export const attributionStats = {
  runtimeCount: 31,
  developmentCount: 9,
  totalCount: 40,
}
