/** Spanish display titles for catalog items. English comes from catalog.ts. */
export const catalogItemTitlesEs: Record<string, string> = {
  init: "Inicialización",
  "project-setup": "Configuración del proyecto",
  theme: "Tema",
  utils: "Utilidades",
  i18n: "i18n",
  attributions: "Atribuciones",
  button: "Botón",
  "button-group": "Grupo de botones",
  toggle: "Interruptor",
  "toggle-group": "Grupo de interruptores",
  input: "Entrada",
  textarea: "Área de texto",
  label: "Etiqueta",
  checkbox: "Casilla",
  "radio-group": "Grupo de opciones",
  switch: "Switch",
  select: "Selector",
  "native-select": "Selector nativo",
  slider: "Deslizador",
  "input-otp": "Entrada OTP",
  "input-group": "Grupo de entrada",
  field: "Campo",
  form: "Formulario",
  combobox: "Combobox",
  "date-picker": "Selector de fecha",
  card: "Tarjeta",
  layout: "Layout",
  separator: "Separador",
  "aspect-ratio": "Relación de aspecto",
  "scroll-area": "Área de desplazamiento",
  resizable: "Redimensionable",
  direction: "Dirección",
  tabs: "Pestañas",
  accordion: "Acordeón",
  breadcrumb: "Miga de pan",
  "navigation-menu": "Menú de navegación",
  menubar: "Barra de menú",
  pagination: "Paginación",
  sidebar: "Barra lateral",
  dialog: "Diálogo",
  "alert-dialog": "Diálogo de alerta",
  sheet: "Panel lateral",
  drawer: "Cajón",
  popover: "Popover",
  "hover-card": "Tarjeta al pasar",
  tooltip: "Tooltip",
  "dropdown-menu": "Menú desplegable",
  "context-menu": "Menú contextual",
  alert: "Alerta",
  badge: "Insignia",
  progress: "Progreso",
  skeleton: "Esqueleto",
  spinner: "Cargador",
  sonner: "Sonner",
  toast: "Toast",
  empty: "Vacío",
  table: "Tabla",
  "data-table": "Tabla de datos",
  chart: "Gráfico",
  calendar: "Calendario",
  carousel: "Carrusel",
  avatar: "Avatar",
  kbd: "Tecla",
  item: "Ítem",
  collapsible: "Colapsable",
  command: "Comando",
  typography: "Tipografía",
  "quality-summary-card": "Tarjeta de resumen de calidad",
  "data-product-table": "Tabla de productos de datos",
  "data-product-card": "Tarjeta de producto de datos",
  hero: "Hero",
  "dataos-sidebar": "Barra lateral de aplicación",
  "application-header": "Encabezado de aplicación",
  "plan-card": "Tarjeta de plan",
  "plan-status-card": "Tarjeta de estado del plan",
  "run-card": "Tarjeta de ejecución",
  "run-duration": "Duración de ejecución",
  "model-health-runs": "Salud del modelo entre ejecuciones",
  "run-metrics": "Métricas de ejecución",
  "models-table": "Tabla de modelos",
  login: "Inicio de sesión",
  signup: "Registro",
  "login-form": "Formulario de acceso",
}

export function catalogItemTitle(
  name: string,
  englishTitle: string,
  language: string
) {
  if (language === "es" || language.startsWith("es")) {
    return catalogItemTitlesEs[name] ?? englishTitle
  }
  return englishTitle
}
