import type { CatalogCategory } from "@/app/catalog"

export const chartCatalogCategories: CatalogCategory[] = [
  {
    id: "charts-area",
    title: "Charts · Area",
    items: [
      {
        name: "chart-area-axes",
        title: "Area Chart Axes",
        description: "shadcn area axes chart block.",
        install: "npx shadcn@latest add @modernui/chart-area-axes\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-area-axes",
      },
      {
        name: "chart-area-default",
        title: "Area Chart Default",
        description: "shadcn area default chart block.",
        install: "npx shadcn@latest add @modernui/chart-area-default\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-area-default",
      },
      {
        name: "chart-area-gradient",
        title: "Area Chart Gradient",
        description: "shadcn area gradient chart block.",
        install: "npx shadcn@latest add @modernui/chart-area-gradient\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-area-gradient",
      },
      {
        name: "chart-area-icons",
        title: "Area Chart Icons",
        description: "shadcn area icons chart block.",
        install: "npx shadcn@latest add @modernui/chart-area-icons\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-area-icons",
      },
      {
        name: "chart-area-interactive",
        title: "Area Chart Interactive",
        description: "shadcn area interactive chart block.",
        install: "npx shadcn@latest add @modernui/chart-area-interactive\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-area-interactive",
      },
      {
        name: "chart-area-legend",
        title: "Area Chart Legend",
        description: "shadcn area legend chart block.",
        install: "npx shadcn@latest add @modernui/chart-area-legend\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-area-legend",
      },
      {
        name: "chart-area-linear",
        title: "Area Chart Linear",
        description: "shadcn area linear chart block.",
        install: "npx shadcn@latest add @modernui/chart-area-linear\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-area-linear",
      },
      {
        name: "chart-area-stacked",
        title: "Area Chart Stacked",
        description: "shadcn area stacked chart block.",
        install: "npx shadcn@latest add @modernui/chart-area-stacked\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-area-stacked",
      },
      {
        name: "chart-area-stacked-expand",
        title: "Area Chart Stacked Expand",
        description: "shadcn area stacked expand chart block.",
        install: "npx shadcn@latest add @modernui/chart-area-stacked-expand\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-area-stacked-expand",
      },
      {
        name: "chart-area-step",
        title: "Area Chart Step",
        description: "shadcn area step chart block.",
        install: "npx shadcn@latest add @modernui/chart-area-step\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-area-step",
      },
    ],
  },
  {
    id: "charts-bar",
    title: "Charts · Bar",
    items: [
      {
        name: "chart-bar-active",
        title: "Bar Chart Active",
        description: "shadcn bar active chart block.",
        install: "npx shadcn@latest add @modernui/chart-bar-active\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-bar-active",
      },
      {
        name: "chart-bar-default",
        title: "Bar Chart Default",
        description: "shadcn bar default chart block.",
        install: "npx shadcn@latest add @modernui/chart-bar-default\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-bar-default",
      },
      {
        name: "chart-bar-horizontal",
        title: "Bar Chart Horizontal",
        description: "shadcn bar horizontal chart block.",
        install: "npx shadcn@latest add @modernui/chart-bar-horizontal\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-bar-horizontal",
      },
      {
        name: "chart-bar-interactive",
        title: "Bar Chart Interactive",
        description: "shadcn bar interactive chart block.",
        install: "npx shadcn@latest add @modernui/chart-bar-interactive\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-bar-interactive",
      },
      {
        name: "chart-bar-label",
        title: "Bar Chart Label",
        description: "shadcn bar label chart block.",
        install: "npx shadcn@latest add @modernui/chart-bar-label\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-bar-label",
      },
      {
        name: "chart-bar-label-custom",
        title: "Bar Chart Label Custom",
        description: "shadcn bar label custom chart block.",
        install: "npx shadcn@latest add @modernui/chart-bar-label-custom\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-bar-label-custom",
      },
      {
        name: "chart-bar-mixed",
        title: "Bar Chart Mixed",
        description: "shadcn bar mixed chart block.",
        install: "npx shadcn@latest add @modernui/chart-bar-mixed\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-bar-mixed",
      },
      {
        name: "chart-bar-multiple",
        title: "Bar Chart Multiple",
        description: "shadcn bar multiple chart block.",
        install: "npx shadcn@latest add @modernui/chart-bar-multiple\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-bar-multiple",
      },
      {
        name: "chart-bar-negative",
        title: "Bar Chart Negative",
        description: "shadcn bar negative chart block.",
        install: "npx shadcn@latest add @modernui/chart-bar-negative\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-bar-negative",
      },
      {
        name: "chart-bar-stacked",
        title: "Bar Chart Stacked",
        description: "shadcn bar stacked chart block.",
        install: "npx shadcn@latest add @modernui/chart-bar-stacked\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-bar-stacked",
      },
    ],
  },
  {
    id: "charts-line",
    title: "Charts · Line",
    items: [
      {
        name: "chart-line-default",
        title: "Line Chart Default",
        description: "shadcn line default chart block.",
        install: "npx shadcn@latest add @modernui/chart-line-default\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-line-default",
      },
      {
        name: "chart-line-dots",
        title: "Line Chart Dots",
        description: "shadcn line dots chart block.",
        install: "npx shadcn@latest add @modernui/chart-line-dots\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-line-dots",
      },
      {
        name: "chart-line-dots-colors",
        title: "Line Chart Dots Colors",
        description: "shadcn line dots colors chart block.",
        install: "npx shadcn@latest add @modernui/chart-line-dots-colors\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-line-dots-colors",
      },
      {
        name: "chart-line-dots-custom",
        title: "Line Chart Dots Custom",
        description: "shadcn line dots custom chart block.",
        install: "npx shadcn@latest add @modernui/chart-line-dots-custom\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-line-dots-custom",
      },
      {
        name: "chart-line-interactive",
        title: "Line Chart Interactive",
        description: "shadcn line interactive chart block.",
        install: "npx shadcn@latest add @modernui/chart-line-interactive\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-line-interactive",
      },
      {
        name: "chart-line-label",
        title: "Line Chart Label",
        description: "shadcn line label chart block.",
        install: "npx shadcn@latest add @modernui/chart-line-label\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-line-label",
      },
      {
        name: "chart-line-label-custom",
        title: "Line Chart Label Custom",
        description: "shadcn line label custom chart block.",
        install: "npx shadcn@latest add @modernui/chart-line-label-custom\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-line-label-custom",
      },
      {
        name: "chart-line-linear",
        title: "Line Chart Linear",
        description: "shadcn line linear chart block.",
        install: "npx shadcn@latest add @modernui/chart-line-linear\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-line-linear",
      },
      {
        name: "chart-line-multiple",
        title: "Line Chart Multiple",
        description: "shadcn line multiple chart block.",
        install: "npx shadcn@latest add @modernui/chart-line-multiple\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-line-multiple",
      },
      {
        name: "chart-line-step",
        title: "Line Chart Step",
        description: "shadcn line step chart block.",
        install: "npx shadcn@latest add @modernui/chart-line-step\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-line-step",
      },
    ],
  },
  {
    id: "charts-pie",
    title: "Charts · Pie",
    items: [
      {
        name: "chart-pie-donut",
        title: "Pie Chart Donut",
        description: "shadcn pie donut chart block.",
        install: "npx shadcn@latest add @modernui/chart-pie-donut\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-pie-donut",
      },
      {
        name: "chart-pie-donut-active",
        title: "Pie Chart Donut Active",
        description: "shadcn pie donut active chart block.",
        install: "npx shadcn@latest add @modernui/chart-pie-donut-active\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-pie-donut-active",
      },
      {
        name: "chart-pie-donut-text",
        title: "Pie Chart Donut Text",
        description: "shadcn pie donut text chart block.",
        install: "npx shadcn@latest add @modernui/chart-pie-donut-text\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-pie-donut-text",
      },
      {
        name: "chart-pie-interactive",
        title: "Pie Chart Interactive",
        description: "shadcn pie interactive chart block.",
        install: "npx shadcn@latest add @modernui/chart-pie-interactive\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-pie-interactive",
      },
      {
        name: "chart-pie-label",
        title: "Pie Chart Label",
        description: "shadcn pie label chart block.",
        install: "npx shadcn@latest add @modernui/chart-pie-label\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-pie-label",
      },
      {
        name: "chart-pie-label-custom",
        title: "Pie Chart Label Custom",
        description: "shadcn pie label custom chart block.",
        install: "npx shadcn@latest add @modernui/chart-pie-label-custom\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-pie-label-custom",
      },
      {
        name: "chart-pie-label-list",
        title: "Pie Chart Label List",
        description: "shadcn pie label list chart block.",
        install: "npx shadcn@latest add @modernui/chart-pie-label-list\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-pie-label-list",
      },
      {
        name: "chart-pie-legend",
        title: "Pie Chart Legend",
        description: "shadcn pie legend chart block.",
        install: "npx shadcn@latest add @modernui/chart-pie-legend\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-pie-legend",
      },
      {
        name: "chart-pie-separator-none",
        title: "Pie Chart Separator None",
        description: "shadcn pie separator none chart block.",
        install: "npx shadcn@latest add @modernui/chart-pie-separator-none\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-pie-separator-none",
      },
      {
        name: "chart-pie-simple",
        title: "Pie Chart Simple",
        description: "shadcn pie simple chart block.",
        install: "npx shadcn@latest add @modernui/chart-pie-simple\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-pie-simple",
      },
      {
        name: "chart-pie-stacked",
        title: "Pie Chart Stacked",
        description: "shadcn pie stacked chart block.",
        install: "npx shadcn@latest add @modernui/chart-pie-stacked\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-pie-stacked",
      },
    ],
  },
  {
    id: "charts-radar",
    title: "Charts · Radar",
    items: [
      {
        name: "chart-radar-default",
        title: "Radar Chart Default",
        description: "shadcn radar default chart block.",
        install: "npx shadcn@latest add @modernui/chart-radar-default\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radar-default",
      },
      {
        name: "chart-radar-dots",
        title: "Radar Chart Dots",
        description: "shadcn radar dots chart block.",
        install: "npx shadcn@latest add @modernui/chart-radar-dots\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radar-dots",
      },
      {
        name: "chart-radar-grid-circle",
        title: "Radar Chart Grid Circle",
        description: "shadcn radar grid circle chart block.",
        install: "npx shadcn@latest add @modernui/chart-radar-grid-circle\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radar-grid-circle",
      },
      {
        name: "chart-radar-grid-circle-fill",
        title: "Radar Chart Grid Circle Fill",
        description: "shadcn radar grid circle fill chart block.",
        install: "npx shadcn@latest add @modernui/chart-radar-grid-circle-fill\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radar-grid-circle-fill",
      },
      {
        name: "chart-radar-grid-circle-no-lines",
        title: "Radar Chart Grid Circle No Lines",
        description: "shadcn radar grid circle no lines chart block.",
        install: "npx shadcn@latest add @modernui/chart-radar-grid-circle-no-lines\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radar-grid-circle-no-lines",
      },
      {
        name: "chart-radar-grid-custom",
        title: "Radar Chart Grid Custom",
        description: "shadcn radar grid custom chart block.",
        install: "npx shadcn@latest add @modernui/chart-radar-grid-custom\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radar-grid-custom",
      },
      {
        name: "chart-radar-grid-fill",
        title: "Radar Chart Grid Fill",
        description: "shadcn radar grid fill chart block.",
        install: "npx shadcn@latest add @modernui/chart-radar-grid-fill\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radar-grid-fill",
      },
      {
        name: "chart-radar-grid-none",
        title: "Radar Chart Grid None",
        description: "shadcn radar grid none chart block.",
        install: "npx shadcn@latest add @modernui/chart-radar-grid-none\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radar-grid-none",
      },
      {
        name: "chart-radar-icons",
        title: "Radar Chart Icons",
        description: "shadcn radar icons chart block.",
        install: "npx shadcn@latest add @modernui/chart-radar-icons\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radar-icons",
      },
      {
        name: "chart-radar-label-custom",
        title: "Radar Chart Label Custom",
        description: "shadcn radar label custom chart block.",
        install: "npx shadcn@latest add @modernui/chart-radar-label-custom\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radar-label-custom",
      },
      {
        name: "chart-radar-legend",
        title: "Radar Chart Legend",
        description: "shadcn radar legend chart block.",
        install: "npx shadcn@latest add @modernui/chart-radar-legend\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radar-legend",
      },
      {
        name: "chart-radar-lines-only",
        title: "Radar Chart Lines Only",
        description: "shadcn radar lines only chart block.",
        install: "npx shadcn@latest add @modernui/chart-radar-lines-only\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radar-lines-only",
      },
      {
        name: "chart-radar-multiple",
        title: "Radar Chart Multiple",
        description: "shadcn radar multiple chart block.",
        install: "npx shadcn@latest add @modernui/chart-radar-multiple\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radar-multiple",
      },
      {
        name: "chart-radar-radius",
        title: "Radar Chart Radius",
        description: "shadcn radar radius chart block.",
        install: "npx shadcn@latest add @modernui/chart-radar-radius\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radar-radius",
      },
    ],
  },
  {
    id: "charts-radial",
    title: "Charts · Radial",
    items: [
      {
        name: "chart-radial-grid",
        title: "Radial Chart Grid",
        description: "shadcn radial grid chart block.",
        install: "npx shadcn@latest add @modernui/chart-radial-grid\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radial-grid",
      },
      {
        name: "chart-radial-label",
        title: "Radial Chart Label",
        description: "shadcn radial label chart block.",
        install: "npx shadcn@latest add @modernui/chart-radial-label\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radial-label",
      },
      {
        name: "chart-radial-shape",
        title: "Radial Chart Shape",
        description: "shadcn radial shape chart block.",
        install: "npx shadcn@latest add @modernui/chart-radial-shape\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radial-shape",
      },
      {
        name: "chart-radial-simple",
        title: "Radial Chart Simple",
        description: "shadcn radial simple chart block.",
        install: "npx shadcn@latest add @modernui/chart-radial-simple\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radial-simple",
      },
      {
        name: "chart-radial-stacked",
        title: "Radial Chart Stacked",
        description: "shadcn radial stacked chart block.",
        install: "npx shadcn@latest add @modernui/chart-radial-stacked\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radial-stacked",
      },
      {
        name: "chart-radial-text",
        title: "Radial Chart Text",
        description: "shadcn radial text chart block.",
        install: "npx shadcn@latest add @modernui/chart-radial-text\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-radial-text",
      },
    ],
  },
  {
    id: "charts-sparkline",
    title: "Charts · Sparkline",
    items: [
      {
        name: "chart-sparkline-line",
        title: "Sparkline Chart Line",
        description: "Compact line sparkline for KPI cards and table cells.",
        install: "npx shadcn@latest add @modernui/chart-sparkline-line\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-sparkline-line",
      },
      {
        name: "chart-sparkline-area",
        title: "Sparkline Chart Area",
        description: "Filled area sparkline for compact trend visualization.",
        install: "npx shadcn@latest add @modernui/chart-sparkline-area\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-sparkline-area",
      },
    ],
  },
  {
    id: "charts-histogram",
    title: "Charts · Histogram",
    items: [
      {
        name: "chart-histogram-default",
        title: "Histogram Chart Default",
        description: "Distribution chart with zero-gap bars for binned data.",
        install: "npx shadcn@latest add @modernui/chart-histogram-default\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-histogram-default",
      },
      {
        name: "chart-histogram-minimal",
        title: "Histogram Chart Minimal",
        description: "Axis-free histogram with rounded bars and active bin highlight.",
        install: "npx shadcn@latest add @modernui/chart-histogram-minimal\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-histogram-minimal",
      },
      {
        name: "chart-histogram-nav",
        title: "Histogram Chart Nav",
        description: "Paginated histogram with previous and next bin navigation.",
        install: "npx shadcn@latest add @modernui/chart-histogram-nav\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-histogram-nav",
      },
    ],
  },
  {
    id: "charts-scatter",
    title: "Charts · Scatter",
    items: [
      {
        name: "chart-scatter-default",
        title: "Scatter Chart Default",
        description: "Correlation chart with optional bubble sizing via ZAxis.",
        install: "npx shadcn@latest add @modernui/chart-scatter-default\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-scatter-default",
      },
    ],
  },
  {
    id: "charts-composed",
    title: "Charts · Composed",
    items: [
      {
        name: "chart-composed-default",
        title: "Composed Chart Default",
        description: "Bar and line series combined on dual axes.",
        install: "npx shadcn@latest add @modernui/chart-composed-default\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-composed-default",
      },
    ],
  },
  {
    id: "charts-tooltip",
    title: "Charts · Tooltip",
    items: [
      {
        name: "chart-tooltip-advanced",
        title: "Tooltip Chart Advanced",
        description: "shadcn tooltip advanced chart block.",
        install: "npx shadcn@latest add @modernui/chart-tooltip-advanced\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-tooltip-advanced",
      },
      {
        name: "chart-tooltip-default",
        title: "Tooltip Chart Default",
        description: "shadcn tooltip default chart block.",
        install: "npx shadcn@latest add @modernui/chart-tooltip-default\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-tooltip-default",
      },
      {
        name: "chart-tooltip-demo",
        title: "Tooltip Chart Demo",
        description: "shadcn tooltip demo chart block.",
        install: "npx shadcn@latest add @modernui/chart-tooltip-demo\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-tooltip-demo",
      },
      {
        name: "chart-tooltip-formatter",
        title: "Tooltip Chart Formatter",
        description: "shadcn tooltip formatter chart block.",
        install: "npx shadcn@latest add @modernui/chart-tooltip-formatter\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-tooltip-formatter",
      },
      {
        name: "chart-tooltip-icons",
        title: "Tooltip Chart Icons",
        description: "shadcn tooltip icons chart block.",
        install: "npx shadcn@latest add @modernui/chart-tooltip-icons\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-tooltip-icons",
      },
      {
        name: "chart-tooltip-indicator-line",
        title: "Tooltip Chart Indicator Line",
        description: "shadcn tooltip indicator line chart block.",
        install: "npx shadcn@latest add @modernui/chart-tooltip-indicator-line\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-tooltip-indicator-line",
      },
      {
        name: "chart-tooltip-indicator-none",
        title: "Tooltip Chart Indicator None",
        description: "shadcn tooltip indicator none chart block.",
        install: "npx shadcn@latest add @modernui/chart-tooltip-indicator-none\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-tooltip-indicator-none",
      },
      {
        name: "chart-tooltip-label-custom",
        title: "Tooltip Chart Label Custom",
        description: "shadcn tooltip label custom chart block.",
        install: "npx shadcn@latest add @modernui/chart-tooltip-label-custom\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-tooltip-label-custom",
      },
      {
        name: "chart-tooltip-label-formatter",
        title: "Tooltip Chart Label Formatter",
        description: "shadcn tooltip label formatter chart block.",
        install: "npx shadcn@latest add @modernui/chart-tooltip-label-formatter\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-tooltip-label-formatter",
      },
      {
        name: "chart-tooltip-label-none",
        title: "Tooltip Chart Label None",
        description: "shadcn tooltip label none chart block.",
        install: "npx shadcn@latest add @modernui/chart-tooltip-label-none\nnpx shadcn@latest add tmdc-io/modern-ui-component/chart-tooltip-label-none",
      },
    ],
  },
]
